name: grocery_app
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: ^0.20.0-nullsafety.3
  google_maps_flutter: 
  flutter_staggered_grid_view: 0.3.4
  geolocator: ^8.0.3
  geocoder: 
  html:
  http: ^0.13.4
  dio: ^4.0.4
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/categories_images/
    - assets/images/grocery_images/
    - assets/images/beverages_images/
    - assets/icons/
    - assets/icons/account_icons/
    - assets/fonts/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
        - asset: assets/fonts/gilroy/Gilroy-Bold.otf
